In [36]:
import pandas as pd
import numpy as np

In [ ]:
# Q1 Pandas version 

In [2]:
pd.__version__

'2.2.2'

In [ ]:
# Q2 Records count

In [5]:
df = pd.read_csv("data/laptops.csv")
df.shape[0]

2160

In [ ]:
# Q3 Laptop brands

In [12]:
df['Brand'].nunique()

27

In [ ]:
# Q4. Missing values

In [18]:
cols = df.isnull().sum() > 0
cols.sum()

3

In [ ]:
# Q5. Maximum final price

In [21]:
dell_df = df[df['Brand'] == "Dell"]
dell_df['Final Price'].max()

3936.0

In [ ]:
# Q6. Median value of Screen

In [23]:
df['Screen'].median()

15.6

In [28]:
most_freq = df['Screen'].mode().iloc[0]

In [30]:
df['Screen'] = df['Screen'].fillna(most_freq)
df['Screen'].median()

15.6

In [ ]:
# Q7. Sum of weights

In [32]:
innjoo_df = df[df['Brand'] == "Innjoo"]
innjoo_df

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [44]:
selected_df = innjoo_df[['RAM', 'Storage', 'Screen']]
selected_df

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [45]:
X = selected_df.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [46]:
XTX = np.dot(X.T, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [47]:
iXTX = np.linalg.inv(XTX)
iXTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [48]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [49]:
result = np.dot(iXTX, X.T)
w = np.dot(result, y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [50]:
w.sum()

91.29988062995588